version: '3.9'

services:
  web:
    container_name: fileshareFrontend
    build: client
    ports:
      - 3000:3000
    restart: always
  
  db:
    image: mysql:latest
    container_name: fileshareDB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
  server:
    container_name: fileshareServer
    build: server
    ports:
      - 8000:8000
    restart: always
    env_file:
      - server/.env
