version: '3.9'

services:
  web:
    container_name: fileshareFrontend
    build: ./client
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client:/usr/app 

  db:
    image: mysql:8.0
    container_name: fileshareDB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fileshare
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  server:
    container_name: fileshareServer
    build: ./server
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./server/.env
